"""add calendar_account

Revision ID: 1243680ff21b
Revises: b1231d096c2c
Create Date: 2026-08-09 20:53:28.220225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1243680ff21b'
down_revision: Union[str, Sequence[str], None] = 'b1231d096c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('google_account_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_ids_json', sa.JSON(), nullable=True),
    sa.Column('oauth_refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['household_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_account')
    # ### end Alembic commands ###
