"""add email_account, email_triage_log

Revision ID: 3359e04d761b
Revises: 5810ccef540e
Create Date: 2026-08-09 22:45:03.924865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3359e04d761b'
down_revision: Union[str, Sequence[str], None] = '5810ccef540e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('gmail_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oauth_refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['household_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_triage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sa.Enum('spam', 'important', 'normal', 'calendar_candidate', name='emailclassification'), nullable=False),
    sa.Column('action_taken', sa.Enum('trashed', 'flagged', 'calendar_event_created', 'none', name='emailactiontaken'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_account_id', 'gmail_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_triage_log')
    op.drop_table('email_account')
    # ### end Alembic commands ###
