"""add finance domain, plaid tables

Revision ID: 5810ccef540e
Revises: 56c3c6888b23
Create Date: 2026-08-09 22:22:49.030697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5810ccef540e'
down_revision: Union[str, Sequence[str], None] = '56c3c6888b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


OLD_DOMAIN_ENUM = sa.Enum(
    'chore', 'maintenance', 'pet', 'baby', 'bill', 'social', 'prescription', name='domain'
)
NEW_DOMAIN_ENUM = sa.Enum(
    'chore', 'maintenance', 'pet', 'baby', 'bill', 'finance', 'social', 'prescription',
    name='domain',
)


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added: 'finance' domain requires recreating the CHECK
    # constraint SQLite generates for a SQLAlchemy Enum column (autogenerate
    # does not detect enum value changes).
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column(
            'domain', existing_type=OLD_DOMAIN_ENUM, type_=NEW_DOMAIN_ENUM, existing_nullable=False
        )
    with op.batch_alter_table('auto_approve_rule', schema=None) as batch_op:
        batch_op.alter_column(
            'domain', existing_type=OLD_DOMAIN_ENUM, type_=NEW_DOMAIN_ENUM, existing_nullable=False
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_amount_cents', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Enum('user', 'agent', name='budgetcreatedby'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linked_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('plaid_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plaid_access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plaid_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sync_cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_mask', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['household_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['linked_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_plaid_transaction_id'), 'transaction', ['plaid_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_plaid_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('linked_account')
    op.drop_table('budget_category')
    # ### end Alembic commands ###

    with op.batch_alter_table('auto_approve_rule', schema=None) as batch_op:
        batch_op.alter_column(
            'domain', existing_type=NEW_DOMAIN_ENUM, type_=OLD_DOMAIN_ENUM, existing_nullable=False
        )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column(
            'domain', existing_type=NEW_DOMAIN_ENUM, type_=OLD_DOMAIN_ENUM, existing_nullable=False
        )
