"""initial schema

Revision ID: b1231d096c2c
Revises: 
Create Date: 2026-08-09 17:41:15.326149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1231d096c2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_approve_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('chore', 'maintenance', 'pet', 'baby', 'bill', 'social', 'prescription', name='domain'), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('chore', 'maintenance', 'pet', 'baby', 'bill', 'social', 'prescription', name='domain'), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'skipped', 'cancelled', name='status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='priority'), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Enum('user', 'agent', name='createdby'), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('due_date_only', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_occurrence_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('last_nudged_at', sa.DateTime(), nullable=True),
    sa.Column('nudge_count', sa.Integer(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['household_member.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['household_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('calendar_create', 'bill_pay', 'order_supply', 'book_appointment', 'send_message', name='actiontype'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'expired', 'executed', 'failed', name='actionstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nudge_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('twilio_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['household_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nudge_log')
    op.drop_table('action_request')
    op.drop_table('item')
    op.drop_table('household_member')
    op.drop_table('auto_approve_rule')
    # ### end Alembic commands ###
